project:
  type: website
  output-dir: docs

website:
  title: "Gian de Lima Santos"
  reader-mode: true
  navbar:
    background: "#FFFFFF" # white
    foreground: "#133F87" # blue
    search: true
    pinned: true
    right:
      - about.qmd
      - icon: github
        href: https://github.com/gianlima
      - icon: twitter
        href: https://twitter.com/MattCrumpLab
format:
  html:
    theme: 
      - morph
      - custom.scss
    css: styles.css

editor: visual

